#CI nivel 02 -  Disparar o Pieline automaticamente em periodos definidos

# This is a basic workflow that is manually triggered

name: 'Execucao Agendada'

#triggers gatilhos de ecxec 
on:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  e2e-tests:

   runs-on: ubuntu-latest


   steps:
     - uses: actions/checkout@v4

     - name: Instalando yarn
       run: npm install -g yarn

     - name: Instalando dependencias
       run: yarn

     - name: Instalando playwright
       run: yarn playwright install

     - name: Testes E2E (end-to-end) 
       run: yarn run e2e

     # passed, failed, cancelled
     - uses: actions/upload-artifact@v4
       if: ${{ !cancelled() }}
       with:
         name: relatorio-de-testes
         path: ./playwright-report