#CI nivel 03 -  Disparar o Pieline automaticamente sempre que outro wf for concluido, como deploy

# This is a basic workflow that is manually triggered

name: 'Execucao por Deploy'

#triggers gatilhos de ecxec 
on:
  workflow_run:
    workflows: ['Execucao Manual']
    types:
      - completed

jobs:
  e2e-tests:

   runs-on: ubuntu-latest


   steps:
     - uses: actions/checkout@v4

     - name: Instalando yarn
       run: npm install -g yarn

     - name: Instalando dependencias
       run: yarn

     - name: Instalando playwright
       run: yarn playwright install

     - name: Testes E2E (end-to-end) 
       run: yarn run e2e

     # passed, failed, cancelled
     - uses: actions/upload-artifact@v4
       if: ${{ !cancelled() }}
       with:
         name: relatorio-de-testes
         path: ./playwright-report